# ---
# variables
# ---

# ...

# ---
# commands (start/build)
# ---

install:
	npm i

dev:
	npm run dev

build:
	npm run build

format:
	npx @biomejs/biome format --write .

lint:
	npx @biomejs/biome lint --apply .

run:
	npm start

# ---
# commands (example)
# ---

run-example:
	npm run run-example
