# ---
# variables
# ---

# ...

# ---
# commands (start/build)
# ---

install:
	npm i

dev:
	npm run dev

build:
	npm run build

run:
	npm start

# ---
# commands (example)
# ---

run-example:
	npm run run-example
