[workspace]

members = [
    "rs/actix-postgres-example",
    "rs/axum-postgres-example",
    "rs/async-graphql-warp-postgres-example",
    "rs/gotham-postgres-example",
    "rs/juniper-warp-postgres-example",
    "rs/warp-postgres-example",
]
