// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Jutsu struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	ChakraNature string `json:"chakra_nature"`
	Description  string `json:"description"`
}

type JutsuNew struct {
	Name         string  `json:"name"`
	ChakraNature string  `json:"chakra_nature"`
	Description  *string `json:"description"`
}

type JutsuUpdates struct {
	Name         *string `json:"name"`
	ChakraNature *string `json:"chakra_nature"`
	Description  *string `json:"description"`
}

type Ninja struct {
	ID        int      `json:"id"`
	FirstName string   `json:"first_name"`
	LastName  string   `json:"last_name"`
	Jutsus    []*Jutsu `json:"jutsus"`
}

type NinjaNew struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type NinjaUpdates struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
}
