# ---
# variables
# ---

# None

# ---
# commands (start/build)
# ---

.PHONY: install dev run run-example

install:
	npm i

# gen:
# 	grpc_tools_node_protoc \
# 	--js_out=import_style=common,binary:. \
# 	--grpc_out=grpc_js:. \
# 	person.proto

dev:
	npm run dev

run:
	npm start

# ---
# commands (example)
# ---

run-example:
	npm run run-example