type Query {
  # get a jutsu by id
  jutsu(id: ID!): Jutsu
}

type Mutation {
  # create new jutsu
  insertJutsu(jutsu: JutsuNew!): Jutsu
  # update an existing jutsu
  updateJutsu(id: ID!, updates: JutsuUpdates): Jutsu
  # soft delete an existing jutsu
  deleteJutsu(id: ID!): Jutsu
}

type Jutsu {
  # unique id
  id: ID!
  # name of jutsu
  name: String!
  # chakra nature of jutsu
  chakra_nature: String!
  # description of jutsu
  description: String!
}

input JutsuNew {
  name: String!
  chakra_nature: String!
  description: String
}

input JutsuUpdates {
  name: String
  chakra_nature: String
  description: String
}
