type Query {
  ninja(id: ID!): Ninja
}

type Mutation {
  insertNinja(ninja: NinjaNew!): Ninja
  updateNinja(id: ID!, updates: NinjaUpdates): Ninja
  deleteNinja(id: ID!): Ninja
  addKnownJutsu(ninja_id: ID!, jutsu_id: ID!): Ninja
  removeKnownJutsu(ninja_id: ID!, jutsu_id: ID!): Ninja
}

type Ninja {
  # unique id
  id: ID!
  # first name
  first_name: String!
  # last name
  last_name: String!
  # jutsu known by ninja
  jutsus: [Jutsu!]
}

input NinjaNew {
  first_name: String!
  last_name: String!
}

input NinjaUpdates {
  # fields that can be updated
  first_name: String
  last_name: String
}
